# Generated by Django 2.0.5 on 2018-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_todos', '0002_auto_20181124_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
