# Generated by Django 2.0.5 on 2018-11-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_todos', '0004_auto_20181125_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('-added_at',)},
        ),
    ]
